version: '3.8'
services:
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=pf2e_gdm_2024!
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
  