import { seedLocalActions } from "./seed-action";
import { seedLocalAncestries } from "./seed-ancestry";
import { seedLocalDomains } from "./seed-domain";
import { seedLocalDeities } from "./seed-deity";
import { seedLocalHeritages } from "./seed-heritage";
import { seedLocalArmorBase } from "./seed-armor-base";
import { seedLocalArmorGroup } from "./seed-armor-group";
import { seedLocalCharacterClass } from "./seed-character-class";
import { seedLocalCharacters } from "./seed-characters";
import { seedLocalLanguages } from "./seed-languages";
import { seedLocalSkills } from "./seed-skill";
import { seedLocalBackgrounds } from "./seed-background";
import { seedLocalTraits } from "./seed-traits";
import { seedLocalUsers } from "./seed-users";
import { seedLocalWeaponBase } from "./seed-weapon-base";
import { seedLocalWeaponCriticalSpecialization } from "./seed-weapon-critical-specialization";
import { seedLocalWeaponGroup } from "./seed-weapon-group";

export const seedLocal = async () => {
  await seedLocalUsers();
  await seedLocalTraits();
  await seedLocalLanguages();
  await seedLocalAncestries();
  await seedLocalHeritages();
  await seedLocalCharacterClass();
  await seedLocalCharacters();
  await seedLocalWeaponCriticalSpecialization();
  await seedLocalWeaponGroup();
  await seedLocalWeaponBase();
  await seedLocalArmorGroup();
  await seedLocalArmorBase();
  await seedLocalSkills();
  await seedLocalBackgrounds();
  await seedLocalActions();
  await seedLocalDomains();
  await seedLocalDeities();
};
