import {
  Attribute,
  DeitySanctification,
  DivineFont,
  Prisma,
  Rarity,
} from "@prisma/client";
import prisma from "../../../src/integrations/prisma/prisma-client";
import { skillIds } from "./seed-skill";
import { weaponBaseIds } from "./seed-weapon-base";
import { domainIds } from "./seed-domain";

export const deityIds = {
  pharasma:     "cmoj8boj00012kwgy34hrat72",
  sarenrae:     "cmoj8boj00013kwgyfsd3ata1",
  iomedae:      "cmoj8boj00014kwgya6wa35gt",
  gozreh:       "cmoj8boj00015kwgya7wt682j",
  caydenCailean:"cmoj8boj00016kwgyf0fm9lag",
  desna:        "cmoj8boj00017kwgyhne84ygv",
  erastil:      "cmoj8boj00018kwgy6di2aaxo",
  torag:        "cmoj8boj00019kwgy3doe28mg",
  asmodeus:     "cmoj8boj0001akwgyen8r8msh",
  urgathoa:     "cmoj8boj0001bkwgyct056nf6",
  norgorber:    "cmoj8boj0001ckwgyb0svb5ae",
  zonKuthon:    "cmoj8boj0001dkwgyaj7kf0ag",
};

const buildLocalDeities = (): Prisma.DeityUncheckedCreateInput[] => [
  {
    id: deityIds.pharasma,
    name: "Pharasma",
    description: "The Lady of Graves judges the souls of the dead, presiding over birth, death, and fate.",
    rarity: Rarity.Common,
    edicts: ["Lay the dead to rest", "Protect the living from undead", "Offer care to the dying"],
    anathema: ["Create undead", "Desecrate a cemetery", "Deny a soul its rest"],
    divineAttributes: [Attribute.Wisdom, Attribute.Charisma],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.HarmOrHeal,
    divineSkillId: skillIds.medicine,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.death },
      { id: domainIds.fate },
      { id: domainIds.healing },
      { id: domainIds.knowledge },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.nightmares },
      { id: domainIds.undeath },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.sarenrae,
    name: "Sarenrae",
    description: "The Dawnflower is a goddess of the sun, redemption, honesty, and healing.",
    rarity: Rarity.Common,
    edicts: ["Bring light to the darkness", "Offer redemption to the wicked", "Heal the sick and wounded"],
    anathema: ["Refuse redemption to a truly repentant soul", "Lie", "Create undead"],
    divineAttributes: [Attribute.Wisdom, Attribute.Charisma],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.Heal,
    divineSkillId: skillIds.religion,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.fire },
      { id: domainIds.healing },
      { id: domainIds.sun },
      { id: domainIds.truth },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.passion },
      { id: domainIds.perfection },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.iomedae,
    name: "Iomedae",
    description: "The Last Azlanti is a goddess of valor, rulership, justice, and honor.",
    rarity: Rarity.Common,
    edicts: ["Be honorable and just", "Protect the weak", "Strive to be a worthy vessel of Iomedae's power"],
    anathema: ["Abandon a companion in need", "Lie", "Commit an act of cowardice"],
    divineAttributes: [Attribute.Strength, Attribute.Charisma],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.Heal,
    divineSkillId: skillIds.intimidation,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.confidence },
      { id: domainIds.might },
      { id: domainIds.truth },
      { id: domainIds.zeal },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.death },
      { id: domainIds.perfection },
      { id: domainIds.protection },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.gozreh,
    name: "Gozreh",
    description: "The Wind and the Waves is a dual-natured deity of nature, the sea, and the weather.",
    rarity: Rarity.Common,
    edicts: ["Respect nature", "Do not over-hunt or over-fish", "Leave settlements that offend the natural world"],
    anathema: ["Pollute natural places", "Destroy natural creatures without need", "Dam or divert rivers permanently"],
    divineAttributes: [Attribute.Strength, Attribute.Wisdom],
    sanctification: DeitySanctification.None,
    divineFont: DivineFont.HarmOrHeal,
    divineSkillId: skillIds.nature,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.air },
      { id: domainIds.nature },
      { id: domainIds.travel },
      { id: domainIds.water },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.destruction },
      { id: domainIds.earth },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.caydenCailean,
    name: "Cayden Cailean",
    description: "The Accidental God is a deity of freedom, ale, wine, and bravery.",
    rarity: Rarity.Common,
    edicts: ["Drink deeply and enjoy life", "Free those who are unjustly imprisoned", "Face danger with courage"],
    anathema: ["Waste alcohol", "Refuse a reasonable request for ale", "Force someone to act against their free will"],
    divineAttributes: [Attribute.Strength, Attribute.Charisma],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.Heal,
    divineSkillId: skillIds.athletics,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.cities },
      { id: domainIds.freedom },
      { id: domainIds.indulgence },
      { id: domainIds.might },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.confidence },
      { id: domainIds.travel },
      { id: domainIds.zeal },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.desna,
    name: "Desna",
    description: "The Song of the Spheres is a goddess of dreams, stars, travelers, and luck.",
    rarity: Rarity.Common,
    edicts: ["Travel the world and explore", "Aid fellow travelers", "Protect the innocent from evil"],
    anathema: ["Cause fear in others", "Deny dreams to those who seek them", "Imprison or trap another"],
    divineAttributes: [Attribute.Dexterity, Attribute.Charisma],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.Heal,
    divineSkillId: skillIds.acrobatics,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.dreams },
      { id: domainIds.luck },
      { id: domainIds.moon },
      { id: domainIds.travel },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.freedom },
      { id: domainIds.passion },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.erastil,
    name: "Erastil",
    description: "Old Deadeye is a god of farming, hunting, trade, and family.",
    rarity: Rarity.Common,
    edicts: ["Care for your family and community", "Protect the natural places of the world", "Hunt and farm sustainably"],
    anathema: ["Prioritize yourself over your community", "Despoil nature", "Abandon those in your care"],
    divineAttributes: [Attribute.Strength, Attribute.Wisdom],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.Heal,
    divineSkillId: skillIds.survival,
    favoredWeaponId: weaponBaseIds.longbow,
    domains: { connect: [
      { id: domainIds.earth },
      { id: domainIds.family },
      { id: domainIds.nature },
      { id: domainIds.wealth },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.creation },
      { id: domainIds.passion },
      { id: domainIds.protection },
      { id: domainIds.travel },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.torag,
    name: "Torag",
    description: "The Father of Creation is a god of the forge, protection, and strategy.",
    rarity: Rarity.Common,
    edicts: ["Protect your people and community", "Forge weapons and armor of great quality", "Treat your allies with loyalty"],
    anathema: ["Destroy something of great craftsmanship without necessity", "Abandon your post or family", "Betray a trusted ally"],
    divineAttributes: [Attribute.Strength, Attribute.Wisdom],
    sanctification: DeitySanctification.HolyOnly,
    divineFont: DivineFont.Heal,
    divineSkillId: skillIds.crafting,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.creation },
      { id: domainIds.earth },
      { id: domainIds.family },
      { id: domainIds.protection },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.might },
      { id: domainIds.perfection },
      { id: domainIds.zeal },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.asmodeus,
    name: "Asmodeus",
    description: "The Prince of Darkness is the god of tyranny, slavery, pride, and contracts.",
    rarity: Rarity.Common,
    edicts: ["Pursue power over others", "Follow the letter of agreements", "Punish those who break contracts"],
    anathema: ["Free a slave without compensation", "Break a contract you have made", "Show mercy when it weakens you"],
    divineAttributes: [Attribute.Intelligence, Attribute.Charisma],
    sanctification: DeitySanctification.UnholyOnly,
    divineFont: DivineFont.Harm,
    divineSkillId: skillIds.deception,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.confidence },
      { id: domainIds.darkness },
      { id: domainIds.tyranny },
      { id: domainIds.wealth },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.fire },
      { id: domainIds.might },
      { id: domainIds.trickery },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.urgathoa,
    name: "Urgathoa",
    description: "The Pallid Princess is a goddess of gluttony, disease, and undeath.",
    rarity: Rarity.Common,
    edicts: ["Satiate your hunger and desires", "Create and command undead", "Spread disease"],
    anathema: ["Deny yourself a pleasure out of principle", "Destroy undead", "Starve or fast willingly"],
    divineAttributes: [Attribute.Constitution, Attribute.Charisma],
    sanctification: DeitySanctification.UnholyOnly,
    divineFont: DivineFont.Harm,
    divineSkillId: skillIds.medicine,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.indulgence },
      { id: domainIds.magic },
      { id: domainIds.nightmares },
      { id: domainIds.undeath },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.plague },
      { id: domainIds.sorrow },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.norgorber,
    name: "Norgorber",
    description: "The Reaper of Reputation is a god of greed, secrets, poison, and murder.",
    rarity: Rarity.Common,
    edicts: ["Keep your true identity secret", "Pursue wealth and power through any means", "Kill to cover your tracks"],
    anathema: ["Reveal your true identity", "Pass up an opportunity for profit", "Betray a member of the Norgorber faith"],
    divineAttributes: [Attribute.Intelligence, Attribute.Dexterity],
    sanctification: DeitySanctification.UnholyOnly,
    divineFont: DivineFont.Harm,
    divineSkillId: skillIds.thievery,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.death },
      { id: domainIds.secrecy },
      { id: domainIds.trickery },
      { id: domainIds.wealth },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.fate },
      { id: domainIds.sorrow },
    ]},
    traits: { connect: [] },
  },
  {
    id: deityIds.zonKuthon,
    name: "Zon-Kuthon",
    description: "The Midnight Lord is a god of envy, pain, darkness, and loss.",
    rarity: Rarity.Common,
    edicts: ["Bring pain and suffering to those who have what you desire", "Mutilate your own body", "Create shadows and darkness"],
    anathema: ["Provide comfort to another's pain", "Destroy a shadow creature", "Show mercy to an enemy"],
    divineAttributes: [Attribute.Constitution, Attribute.Charisma],
    sanctification: DeitySanctification.UnholyOnly,
    divineFont: DivineFont.Harm,
    divineSkillId: skillIds.intimidation,
    favoredWeaponId: null,
    domains: { connect: [
      { id: domainIds.darkness },
      { id: domainIds.destruction },
      { id: domainIds.pain },
      { id: domainIds.sorrow },
    ]},
    alternateDomains: { connect: [
      { id: domainIds.death },
      { id: domainIds.nightmares },
      { id: domainIds.tyranny },
    ]},
    traits: { connect: [] },
  },
];

export const seedLocalDeities = async (): Promise<{
  deities: Prisma.DeityUncheckedCreateInput[];
}> => {
  const deities = buildLocalDeities();
  await prisma.$transaction(
    deities.map((deity) => prisma.deity.create({ data: deity }))
  );
  return { deities };
};
