import {
  ActionCost,
  HeighteningKind,
  Prisma,
  Rarity,
  SpellArea,
  SpellComponent,
  SpellSaveType,
  SpellTargetType,
  SpellTradition,
} from "@prisma/client";
import prisma from "../../../src/integrations/prisma/prisma-client";

export const spellIds = {
  heal: "cmp65tqfw0000h2gy988l2rh7",
  harm: "cmp65tqg00001h2gy11gh5hry",
  fireball: "cmp65tqg00002h2gy5jjy51iu",
  magicMissile: "cmp65tqg00003h2gy1bmh57ov",
  shield: "cmp65tqg00004h2gyaaz9czw7",
  telekineticProjectile: "cmp65tqg00005h2gy6bb6618z",
  detectMagic: "cmp65tqg00006h2gyhd8d86ru",
  mageArmor: "cmp65tqg00007h2gyd2j4dawb",
  bless: "cmp65tqg00008h2gyf3tfg7wm",
  bane: "cmp65tqg00009h2gye5ql6rhy",
  sleep: "cmp65tqg0000ah2gyfo5zf4de",
  charm: "cmp65tqg0000bh2gyc0nlchyd",
  daze: "cmp65tqg0000ch2gy172l7hg5",
  light: "cmp65tqg0000dh2gy1pdj0wdd",
  acidSplash: "cmp65tqg0000eh2gyd20hbhak",
  electricArc: "cmp65tqg0000fh2gydsb5eb4d",
  heroism: "cmp65tqg0000gh2gyafl34jyb",
  fly: "cmp65tqg0000hh2gya6agetwu",
  invisibility: "cmp65tqg0000ih2gybz3parnx",
  dispelMagic: "cmp65tqg0000jh2gy8tav5or6",
  resistEnergy: "cmp65tqg1000kh2gy2t6verrs",
  animalForm: "cmp65tqg1000lh2gy0hyn1d5m",
  summonAnimal: "cmp65tqg1000mh2gy7i7q05xi",
  layOnHands: "cmp65tqg1000nh2gy4ezlaeez",
  wish: "cmp65tqg1000oh2gyg4u4g8ww",
};

const buildLocalSpells = (): Prisma.SpellUncheckedCreateInput[] => [
  {
    id: spellIds.heal,
    name: "Heal",
    description:
      "You channel positive energy to heal the living or damage the undead. If the target is a willing living creature, you restore 1d8 Hit Points. If the target is undead, you deal that amount of positive damage to it, and it gets a basic Fortitude save.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Divine, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Somatic],
    actionCost: ActionCost.OneToThree,
    range: "varies",
    targets: "1 willing living creature or 1 undead",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.Fortitude,
    basicSave: true,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 1,
          effect:
            "The amount of healing or damage increases by 1d8, and the extra healing for the 2-action version increases by 8.",
        },
      ],
    },
  },
  {
    id: spellIds.harm,
    name: "Harm",
    description:
      "You channel negative energy to harm the living or heal the undead. If the target is undead, you restore 1d8 Hit Points. If the target is a living creature, you deal that amount of negative damage, and it gets a basic Fortitude save.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Divine],
    rarity: Rarity.Common,
    components: [SpellComponent.Somatic],
    actionCost: ActionCost.OneToThree,
    range: "varies",
    targets: "1 willing undead creature or 1 living creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.Fortitude,
    basicSave: true,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 1,
          effect:
            "The amount of healing or damage increases by 1d8, and the extra damage for the 2-action version increases by 8.",
        },
      ],
    },
  },
  {
    id: spellIds.fireball,
    name: "Fireball",
    description:
      "A roaring blast of fire appears at a spot you designate, dealing 6d6 fire damage to creatures in the area. Each creature in the area must attempt a basic Reflex save.",
    rank: 3,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "500 feet",
    targets: null,
    targetType: SpellTargetType.Area,
    areaType: SpellArea.Burst,
    areaSize: 20,
    savingThrow: SpellSaveType.Reflex,
    basicSave: true,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 1,
          effect: "The damage increases by 2d6.",
        },
      ],
    },
  },
  {
    id: spellIds.magicMissile,
    name: "Magic Missile",
    description:
      "You send a dart of force streaking through the air to unerringly strike its target. The missile deals 1d4+1 force damage. Because the missile is unerring, on a successful attack it strikes its target.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.OneToThree,
    range: "120 feet",
    targets: "1 creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 2,
          effect: "You shoot one additional missile with each action.",
        },
      ],
    },
  },
  {
    id: spellIds.shield,
    name: "Shield",
    description:
      "You raise a magical shield of force. This counts as using the Raise a Shield action, giving you a +1 circumstance bonus to AC until the start of your next turn, but it doesn't require a hand to use.",
    rank: 0,
    isFocus: false,
    traditions: [
      SpellTradition.Arcane,
      SpellTradition.Divine,
      SpellTradition.Occult,
      SpellTradition.Primal,
    ],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal],
    actionCost: ActionCost.One,
    range: null,
    targets: null,
    targetType: SpellTargetType.Self,
    areaType: SpellArea.None,
    duration: "until the start of your next turn",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.telekineticProjectile,
    name: "Telekinetic Projectile",
    description:
      "You hurl a loose, unattended object that you can see at the target. Make a spell attack roll; on a hit, you deal 1d6+spellcasting modifier damage.",
    rank: 0,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "30 feet",
    targets: "1 creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.detectMagic,
    name: "Detect Magic",
    description:
      "You send out a pulse that registers the presence of magic. You receive no information beyond the presence or absence of magic.",
    rank: 1,
    isFocus: false,
    traditions: [
      SpellTradition.Arcane,
      SpellTradition.Divine,
      SpellTradition.Occult,
      SpellTradition.Primal,
    ],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: null,
    targets: null,
    targetType: SpellTargetType.Area,
    areaType: SpellArea.Emanation,
    areaSize: 30,
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.FixedRank,
          bump: 3,
          effect:
            "You learn the school of magic for the highest-rank effect within range that the spell detects.",
        },
        {
          kind: HeighteningKind.FixedRank,
          bump: 4,
          effect:
            "As 3rd rank, but you also pinpoint the source of the highest-rank magic.",
        },
      ],
    },
  },
  {
    id: spellIds.mageArmor,
    name: "Mage Armor",
    description:
      "You ward yourself with shimmering magical energy, gaining a +1 item bonus to AC and a maximum Dexterity modifier of +5.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: null,
    targets: null,
    targetType: SpellTargetType.Self,
    areaType: SpellArea.None,
    duration: "until the next time you make your daily preparations",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 4,
          effect:
            "The item bonus to AC increases by 1, and the maximum Dexterity modifier increases by 1.",
        },
      ],
    },
  },
  {
    id: spellIds.bless,
    name: "Bless",
    description:
      "Blessings from beyond help your companions strike true. You and your allies gain a +1 status bonus to attack rolls while within the emanation.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Divine, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: null,
    targets: null,
    targetType: SpellTargetType.Area,
    areaType: SpellArea.Emanation,
    areaSize: 5,
    duration: "1 minute",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.bane,
    name: "Bane",
    description:
      "You fill the minds of your enemies with doubt. Enemies in the area take a -1 status penalty to attack rolls as long as they remain in the area.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Divine, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: null,
    targets: null,
    targetType: SpellTargetType.Area,
    areaType: SpellArea.Emanation,
    areaSize: 5,
    duration: "1 minute",
    savingThrow: SpellSaveType.Will,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.sleep,
    name: "Sleep",
    description:
      "Each creature in the area becomes drowsy and might fall asleep. Each must attempt a Will save.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "30 feet",
    targets: null,
    targetType: SpellTargetType.Area,
    areaType: SpellArea.Burst,
    areaSize: 5,
    savingThrow: SpellSaveType.Will,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.FixedRank,
          bump: 4,
          effect:
            "The creatures fall unconscious for 1 round on a failure, even if not damaged.",
        },
      ],
    },
  },
  {
    id: spellIds.charm,
    name: "Charm",
    description:
      "You magically compel the target to regard you as a friend. The target must attempt a Will save.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Somatic, SpellComponent.Verbal],
    actionCost: ActionCost.Two,
    range: "30 feet",
    targets: "1 creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    duration: "1 hour",
    savingThrow: SpellSaveType.Will,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.daze,
    name: "Daze",
    description:
      "You cloud the target's mind and daze it with a mental jolt. The target takes mental damage equal to your spellcasting ability modifier (minimum 0).",
    rank: 0,
    isFocus: false,
    traditions: [
      SpellTradition.Arcane,
      SpellTradition.Divine,
      SpellTradition.Occult,
      SpellTradition.Primal,
    ],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "60 feet",
    targets: "1 creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.Will,
    basicSave: true,
    traits: { connect: [] },
  },
  {
    id: spellIds.light,
    name: "Light",
    description:
      "The object glows, casting bright light in a 20-foot radius and dim light for the next 20 feet.",
    rank: 1,
    isFocus: false,
    traditions: [
      SpellTradition.Arcane,
      SpellTradition.Divine,
      SpellTradition.Occult,
      SpellTradition.Primal,
    ],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "touch",
    targets: "1 object of 1 Bulk or less, either unattended or wielded by a willing creature",
    targetType: SpellTargetType.Object,
    areaType: SpellArea.None,
    duration: "until the next time you make your daily preparations",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.acidSplash,
    name: "Acid Splash",
    description:
      "You splash a glob of acid that splatters your target and nearby creatures. Make a spell attack roll against the target.",
    rank: 0,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "30 feet",
    targets: "1 creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 3,
          effect:
            "The initial damage and the persistent acid damage both increase by 1d6, and the splash damage increases by 1.",
        },
      ],
    },
  },
  {
    id: spellIds.electricArc,
    name: "Electric Arc",
    description:
      "An arc of electricity leaps from one target to another. Each creature takes electricity damage with a basic Reflex save.",
    rank: 0,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "30 feet",
    targets: "1 or 2 creatures",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.Reflex,
    basicSave: true,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 1,
          effect: "The damage increases by 1d4+1.",
        },
      ],
    },
  },
  {
    id: spellIds.heroism,
    name: "Heroism",
    description:
      "Bolstering a creature with mystical fortitude, you grant them a +1 status bonus to attack rolls, Perception checks, saving throws, and skill checks.",
    rank: 3,
    isFocus: false,
    traditions: [SpellTradition.Divine, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "touch",
    targets: "1 willing creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    duration: "10 minutes",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        { kind: HeighteningKind.FixedRank, bump: 6, effect: "The status bonus increases to +2." },
        { kind: HeighteningKind.FixedRank, bump: 9, effect: "The status bonus increases to +3." },
      ],
    },
  },
  {
    id: spellIds.fly,
    name: "Fly",
    description:
      "The target can soar through the air. It gains a fly Speed equal to its Speed or 20 feet, whichever is greater.",
    rank: 4,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "touch",
    targets: "1 willing creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    duration: "5 minutes",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.invisibility,
    name: "Invisibility",
    description:
      "Cloaking the target in shadow, you make it invisible. It becomes invisible, gaining the effects of being undetected by all creatures.",
    rank: 2,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Occult],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "touch",
    targets: "1 willing creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    duration: "10 minutes",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.dispelMagic,
    name: "Dispel Magic",
    description:
      "You unravel the magic behind a spell or magic item. Attempt a counteract check against the target.",
    rank: 2,
    isFocus: false,
    traditions: [
      SpellTradition.Arcane,
      SpellTradition.Divine,
      SpellTradition.Occult,
      SpellTradition.Primal,
    ],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "120 feet",
    targets: "1 spell effect or unattended magic item",
    targetType: SpellTargetType.Object,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.resistEnergy,
    name: "Resist Energy",
    description:
      "Magical protection wards a creature against one type of energy. The target gains resistance 5 against acid, cold, electricity, fire, or sonic damage.",
    rank: 2,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Divine, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: "touch",
    targets: "1 willing creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    duration: "10 minutes",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
    heightenings: {
      create: [
        { kind: HeighteningKind.FixedRank, bump: 4, effect: "The resistance increases to 10." },
        { kind: HeighteningKind.FixedRank, bump: 7, effect: "The resistance increases to 15." },
      ],
    },
  },
  {
    id: spellIds.animalForm,
    name: "Animal Form",
    description:
      "You transform into a Medium battle form of an animal. Your gear is absorbed into your form.",
    rank: 2,
    isFocus: false,
    traditions: [SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Two,
    range: null,
    targets: null,
    targetType: SpellTargetType.Self,
    areaType: SpellArea.None,
    duration: "1 minute",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.summonAnimal,
    name: "Summon Animal",
    description:
      "You conjure an animal to fight on your behalf. You summon a creature with the animal trait whose level is -1 or lower to fight on your behalf.",
    rank: 1,
    isFocus: false,
    traditions: [SpellTradition.Arcane, SpellTradition.Primal],
    rarity: Rarity.Common,
    components: [SpellComponent.Verbal, SpellComponent.Somatic],
    actionCost: ActionCost.Three,
    castTimeText: "1 minute",
    range: "30 feet",
    targets: null,
    targetType: SpellTargetType.Area,
    areaType: SpellArea.None,
    duration: "sustained up to 1 minute",
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
  {
    id: spellIds.layOnHands,
    name: "Lay on Hands",
    description:
      "Your hands become infused with positive energy, healing a willing living creature you touch for 6 Hit Points; if you touch an undead creature, it instead takes 1d6 positive damage and is enfeebled 2 until the start of your next turn.",
    rank: 1,
    isFocus: true,
    traditions: [SpellTradition.Divine],
    rarity: Rarity.Common,
    components: [SpellComponent.Somatic],
    actionCost: ActionCost.One,
    range: "touch",
    targets: "1 willing living creature or 1 undead creature",
    targetType: SpellTargetType.Creature,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.Fortitude,
    basicSave: true,
    traits: { connect: [] },
    heightenings: {
      create: [
        {
          kind: HeighteningKind.Interval,
          bump: 1,
          effect:
            "The amount of healing increases by 6, and the damage to undead increases by 1d6.",
        },
      ],
    },
  },
  {
    id: spellIds.wish,
    name: "Wish",
    description:
      "Reality bends as you make a wish for what could be. You can duplicate any arcane spell of 9th rank or lower, or any non-arcane spell of 7th rank or lower.",
    rank: 10,
    isFocus: false,
    traditions: [SpellTradition.Arcane],
    rarity: Rarity.Rare,
    components: [SpellComponent.Verbal],
    actionCost: ActionCost.Three,
    castTimeText: "10 minutes",
    range: null,
    targets: null,
    targetType: SpellTargetType.None,
    areaType: SpellArea.None,
    savingThrow: SpellSaveType.None,
    basicSave: false,
    traits: { connect: [] },
  },
];

export const seedLocalSpells = async (): Promise<{
  spells: Prisma.SpellUncheckedCreateInput[];
}> => {
  const spells = buildLocalSpells();
  await prisma.$transaction(
    spells.map((spell) => prisma.spell.create({ data: spell }))
  );
  return { spells };
};
