import { ActionCost, FeatType, Prisma, Rarity } from "@prisma/client";
import prisma from "../../../src/integrations/prisma/prisma-client";
import { ancestryIds } from "./seed-ancestry";
import { ClassIds } from "./seed-character-class";
import { skillIds } from "./seed-skill";

export const featIds = {
  // Ancestry feats
  naturalAmbition: "cmp0kt54f00007ugy0ev50y6q",
  multitalented: "cmp0kt54h00017ugyhm4q52di",
  unconventionalWeaponry: "cmp0kt54h00027ugyakiv8t2q",
  goblinScuttle: "cmp0kt54h00037ugyaszz0mrx",
  goblinSong: "cmp0kt54h00047ugy6mgwff2j",
  unbreakableGoblin: "cmp0kt54h00057ugycb6ohg8o",
  orcFerocity: "cmp0kt54h00067ugy1e5seqgx",
  orcSuperstition: "cmp0kt54h00077ugy57pj9ou8",
  celestialResistance: "cmp0kt54h00087ugy8n8k3lyu",
  foxForm: "cmp0kt54h00097ugyb384hj6k",
  // Class feats
  powerAttack: "cmp0kt54i000a7ugy44tg9fli",
  suddenCharge: "cmp0kt54i000b7ugyckm95gzi",
  aggressiveBlock: "cmp0kt54i000c7ugyctyfar4r",
  doubleSlice: "cmp0kt54i000d7ugyfukohq4k",
  pointBlankShot: "cmp0kt54i000e7ugy7bg8dfod",
  animalCompanion: "cmp0kt54i000f7ugygthtgio4",
  nimbleDodge: "cmp0kt54i000g7ugy9jd31xob",
  twistTheKnife: "cmp0kt54i000h7ugy94eteug5",
  kiRush: "cmp0kt54i000i7ugy02k1au99",
  stunningFist: "cmp0kt54i000j7ugy74iq6tvi",
  // Skill feats
  assurance: "cmp0kt54i000k7ugy98ru58gj",
  titanWrestler: "cmp0kt54i000l7ugychxchch2",
  intimidatingGlare: "cmp0kt54i000m7ugy5uimdfor",
  battlecry: "cmp0kt54i000n7ugycyy80a6c",
  lieToMe: "cmp0kt54i000o7ugy39gc9ndl",
  bonMot: "cmp0kt54i000p7ugyhjsh5sbl",
  pickpocket: "cmp0kt54i000q7ugy1iqzf48h",
  experiencedSmuggler: "cmp0kt54i000r7ugy1txthqk3",
  forager: "cmp0kt54i000s7ugy397n9bi3",
  oddityIdentification: "cmp0kt54i000t7ugyaz65hxpm",
  // General feats
  toughness: "cmp0kt54i000u7ugya4t68h23",
  fleet: "cmp0kt54i000v7ugyf27c6wq1",
  incredibleInitiative: "cmp0kt54i000w7ugy1bczfzx9",
  diehard: "cmp0kt54i000x7ugy2f3e9xy6",
  fastRecovery: "cmp0kt54j000y7ugy6fyea24q",
  featherStep: "cmp0kt54j000z7ugy49lre514",
  cannyAcumen: "cmp0kt54j00107ugy4grxfd8v",
  armorProficiency: "cmp0kt54j00117ugyb88v0sna",
  weaponProficiency: "cmp0kt54j00127ugybznm72s4",
  ancestralParagon: "cmp0kt54j00137ugy53u72g12",
  // Bonus feats
  attackOfOpportunity: "cmp0kt54j00147ugyfwgceahf",
  shieldBlock: "cmp0kt54j00157ugy26xb6i2z",
  reactiveShield: "cmp0kt54j00167ugydep33sdr",
  quickShieldBlock: "cmp0kt54j00177ugy9zgdghoq",
  battleMedicine: "cmp0kt54j00187ugy6vm53fee",
  breathControl: "cmp0kt54j00197ugy91v28loe",
  courtlyGraces: "cmp0kt54j001a7ugy1j6e9fyv",
  quickDraw: "cmp0kt54j001b7ugy69505qyo",
  riskySurgery: "cmp0kt54j001c7ugy7ogf4vdu",
  terrifyingResistance: "cmp0kt54j001d7ugyhjyobi0h",
  naturalSkill: "cmp0kt54j001e7ugy0cyt175n",
  sureFooting: "cmp0kt54j001f7ugycllc6djy",
};

const buildLocalFeats = (): Prisma.FeatUncheckedCreateInput[] => [
  // ── Ancestry feats ──────────────────────────────────────────────────────────
  {
    id: featIds.naturalAmbition,
    name: "Natural Ambition",
    description:
      "You were raised to be ambitious and to always strive for more. You gain a 1st-level class feat for your class.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.human,
    traits: { connect: [] },
  },
  {
    id: featIds.multitalented,
    name: "Multitalented",
    description:
      "You've learned to mix approaches from different training methodologies. You gain a 2nd-level multiclass dedication feat.",
    featType: FeatType.Ancestry,
    level: 5,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.human,
    traits: { connect: [] },
  },
  {
    id: featIds.unconventionalWeaponry,
    name: "Unconventional Weaponry",
    description:
      "You've familiarized yourself with a weapon uncommon for your ancestry. Choose an uncommon weapon — you gain access to it and are trained with it.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.human,
    traits: { connect: [] },
  },
  {
    id: featIds.goblinScuttle,
    name: "Goblin Scuttle",
    description:
      "You take advantage of an opportunity to skitter out of harm's way. You move up to half your Speed.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.goblin,
    trigger: "An ally ends a move action adjacent to you.",
    traits: { connect: [] },
  },
  {
    id: featIds.goblinSong,
    name: "Goblin Song",
    description:
      "You sing irritating goblin songs, distracting your foes with silly and catchy lyrics. Attempt a Performance check against the Will DC of a single enemy within 30 feet.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.goblin,
    traits: { connect: [] },
  },
  {
    id: featIds.unbreakableGoblin,
    name: "Unbreakable Goblin",
    description:
      "You can bounce back from disasters. Increase your maximum HP by your level. The DC of recovery checks is equal to 9 + your dying value.",
    featType: FeatType.Ancestry,
    level: 3,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.goblin,
    traits: { connect: [] },
  },
  {
    id: featIds.orcFerocity,
    name: "Orc Ferocity",
    description:
      "Once per day, when you would be reduced to 0 HP but not immediately slain, you can end effects causing you to be sickened and frightened, then stabilize with 1 HP.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.orc,
    frequency: "Once per day",
    trigger: "You would be reduced to 0 HP but not immediately slain.",
    traits: { connect: [] },
  },
  {
    id: featIds.orcSuperstition,
    name: "Orc Superstition",
    description:
      "Your mystical superstitions give you strength against magic. When you succeed at a saving throw against a spell or magical effect, you gain a +1 circumstance bonus to your next attack roll.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.orc,
    trigger: "You succeed at a saving throw against a spell or magical effect.",
    traits: { connect: [] },
  },
  {
    id: featIds.celestialResistance,
    name: "Celestial Resistance",
    description:
      "Your celestial heritage grants you innate protection. You gain resistance 5 to negative damage.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.aasimar,
    traits: { connect: [] },
  },
  {
    id: featIds.foxForm,
    name: "Fox Form",
    description:
      "You transform into a fox, gaining a jaws Strike (1d6 piercing, agile, finesse) and a Speed of 40 feet.",
    featType: FeatType.Ancestry,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    ancestryId: ancestryIds.kitsune,
    traits: { connect: [] },
  },

  // ── Class feats ─────────────────────────────────────────────────────────────
  {
    id: featIds.powerAttack,
    name: "Power Attack",
    description:
      "You unleash a particularly powerful attack. Make a melee Strike. This attack counts as two attacks when calculating your multiple attack penalty. If this Strike hits, you deal an extra die of weapon damage.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.Two,
    rarity: Rarity.Common,
    characterClassId: ClassIds.fighter,
    traits: { connect: [] },
  },
  {
    id: featIds.suddenCharge,
    name: "Sudden Charge",
    description:
      "With a quick sprint, you dash up to your foe and swing. Stride twice. If you end your movement within melee reach of at least one enemy, you can make a melee Strike against that enemy.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.Two,
    rarity: Rarity.Common,
    characterClassId: ClassIds.fighter,
    traits: { connect: [] },
  },
  {
    id: featIds.aggressiveBlock,
    name: "Aggressive Block",
    description:
      "You push back as you block the attack. When you Shield Block, the creature that triggered your reaction must succeed at a Fortitude save or be pushed 5 feet away from you.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    characterClassId: ClassIds.fighter,
    trigger: "You use Shield Block.",
    traits: { connect: [] },
  },
  {
    id: featIds.doubleSlice,
    name: "Double Slice",
    description:
      "You lash out at your foe with both weapons. Make two Strikes, one with each of your two weapons, each using your current multiple attack penalty.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.Two,
    rarity: Rarity.Common,
    characterClassId: ClassIds.fighter,
    requirements: "You are wielding two melee weapons, each in a different hand.",
    traits: { connect: [] },
  },
  {
    id: featIds.pointBlankShot,
    name: "Point-Blank Shot",
    description:
      "You take aim to pick off nearby enemies quickly. When using a ranged volley weapon while in this stance, you don't take the penalty for shooting into your target's reach.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    characterClassId: ClassIds.ranger,
    traits: { connect: [] },
  },
  {
    id: featIds.animalCompanion,
    name: "Animal Companion",
    description:
      "You gain the service of a young animal companion that accompanies you on your adventures and obeys your commands.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    characterClassId: ClassIds.ranger,
    traits: { connect: [] },
  },
  {
    id: featIds.nimbleDodge,
    name: "Nimble Dodge",
    description:
      "You deftly dodge out of the way, gaining a +2 circumstance bonus to AC against the triggering attack.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    characterClassId: ClassIds.rogue,
    trigger: "A creature targets you with an attack and you can see the attacker.",
    requirements: "You are not encumbered.",
    traits: { connect: [] },
  },
  {
    id: featIds.twistTheKnife,
    name: "Twist the Knife",
    description:
      "When you deal a Strike that causes persistent bleed damage, you can increase it. Increase that persistent bleed damage by 1d6.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    characterClassId: ClassIds.rogue,
    traits: { connect: [] },
  },
  {
    id: featIds.kiRush,
    name: "Ki Rush",
    description:
      "You move with the speed and force of rushing water. Move up to twice your Speed. This movement doesn't trigger reactions.",
    featType: FeatType.Class,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    characterClassId: ClassIds.monk,
    traits: { connect: [] },
  },
  {
    id: featIds.stunningFist,
    name: "Stunning Fist",
    description:
      "The focused power of your flurry threatens to overwhelm your opponent. When you target the same creature with two Strikes from Flurry of Blows and both hit, the target must succeed at a Fortitude save or be stunned 1.",
    featType: FeatType.Class,
    level: 4,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    characterClassId: ClassIds.monk,
    traits: { connect: [] },
  },

  // ── Skill feats ─────────────────────────────────────────────────────────────
  {
    id: featIds.assurance,
    name: "Assurance",
    description:
      "Even in the worst circumstances, you can perform basic tasks. Choose a skill — when rolling that skill, you can forgo rolling and use a result of 10 + your proficiency bonus instead.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.athletics,
    traits: { connect: [] },
  },
  {
    id: featIds.titanWrestler,
    name: "Titan Wrestler",
    description:
      "You can attempt to Disarm, Grapple, Reposition, Shove, or Trip creatures up to two sizes larger than you.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.athletics,
    prerequisites: "Trained in Athletics",
    traits: { connect: [] },
  },
  {
    id: featIds.intimidatingGlare,
    name: "Intimidating Glare",
    description:
      "You can Demoralize with a mere glare. When you Demoralize, you can make your Intimidation check without speaking and without the target being able to hear you.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.intimidation,
    traits: { connect: [] },
  },
  {
    id: featIds.battlecry,
    name: "Battlecry",
    description:
      "When you enter battle, you scream a mighty battlecry. You Demoralize all enemies in a 30-foot cone.",
    featType: FeatType.Skill,
    level: 7,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    skillId: skillIds.intimidation,
    prerequisites: "Master in Intimidation",
    traits: { connect: [] },
  },
  {
    id: featIds.lieToMe,
    name: "Lie to Me",
    description:
      "You can use Deception to figure out whether someone else is lying. When someone attempts to Lie to you, attempt a Deception check against their Deception DC.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.deception,
    prerequisites: "Trained in Deception",
    traits: { connect: [] },
  },
  {
    id: featIds.bonMot,
    name: "Bon Mot",
    description:
      "You launch a witty quip at a foe, distracting them. Attempt a Diplomacy check against the Will DC of an enemy within 30 feet. On a success, the target takes a -2 circumstance penalty to Perception and Will saves for 1 minute.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    skillId: skillIds.diplomacy,
    prerequisites: "Trained in Diplomacy",
    traits: { connect: [] },
  },
  {
    id: featIds.pickpocket,
    name: "Pickpocket",
    description:
      "You can Steal or Palm an Object more effectively. You can Steal something from a creature in combat without taking a penalty to your check, though it is still more difficult to steal from alert creatures.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.thievery,
    prerequisites: "Trained in Thievery",
    traits: { connect: [] },
  },
  {
    id: featIds.experiencedSmuggler,
    name: "Experienced Smuggler",
    description:
      "You often move things past the authorities. When you Conceal an Object, treat any check result worse than a success as a success instead.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.thievery,
    prerequisites: "Trained in Thievery",
    traits: { connect: [] },
  },
  {
    id: featIds.forager,
    name: "Forager",
    description:
      "You are particularly skilled at finding food in the wilderness. When you Subsist in the wilderness, if you roll any result worse than a success, you get a success instead.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.survival,
    prerequisites: "Trained in Survival",
    traits: { connect: [] },
  },
  {
    id: featIds.oddityIdentification,
    name: "Oddity Identification",
    description:
      "You have a talent for identifying supernatural oddities. You gain a +2 circumstance bonus to Occultism checks to Recall Knowledge about curses, haunts, and psionics.",
    featType: FeatType.Skill,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    skillId: skillIds.occultism,
    prerequisites: "Trained in Occultism",
    traits: { connect: [] },
  },

  // ── General feats ────────────────────────────────────────────────────────────
  {
    id: featIds.toughness,
    name: "Toughness",
    description:
      "You can withstand more punishment than most. Increase your maximum HP by your level. The DC of recovery checks is equal to 9 + your dying value.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.fleet,
    name: "Fleet",
    description: "You move more quickly. Your Speed increases by 5 feet.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.incredibleInitiative,
    name: "Incredible Initiative",
    description:
      "You react with particularly swift action when a fight breaks out. You gain a +2 circumstance bonus to initiative rolls.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.diehard,
    name: "Diehard",
    description:
      "It takes more to kill you than most. You can remain conscious as a dying creature up to dying 4, though you still die at dying 5.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.fastRecovery,
    name: "Fast Recovery",
    description:
      "Your body quickly bounces back from afflictions. Your recovery time from disease and poison is halved.",
    featType: FeatType.General,
    level: 3,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    prerequisites: "Constitution 14",
    traits: { connect: [] },
  },
  {
    id: featIds.featherStep,
    name: "Feather Step",
    description: "You step carefully and quickly. You can Step into difficult terrain.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    prerequisites: "Dexterity 14",
    traits: { connect: [] },
  },
  {
    id: featIds.cannyAcumen,
    name: "Canny Acumen",
    description:
      "Your avoidance or observation is beyond the ken of most of your kind. Choose Fortitude saves, Reflex saves, Will saves, or Perception. You become an expert in the chosen statistic.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.armorProficiency,
    name: "Armor Proficiency",
    description:
      "You become trained in light armor. If you're already trained in light armor, you become trained in medium armor instead, and so on.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.weaponProficiency,
    name: "Weapon Proficiency",
    description:
      "You become trained in all simple weapons, or if already trained, in all martial weapons, or if already trained, in one advanced weapon group of your choice.",
    featType: FeatType.General,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.ancestralParagon,
    name: "Ancestral Paragon",
    description:
      "Whether through instinct, study, or sheer perseverance, you've come into your own as a member of your ancestry. You gain a 1st-level ancestry feat.",
    featType: FeatType.General,
    level: 3,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },

  // ── Bonus feats ──────────────────────────────────────────────────────────────
  {
    id: featIds.attackOfOpportunity,
    name: "Attack of Opportunity",
    description:
      "Ever-watchful for weaknesses, you can quickly exploit momentary distractions. When a creature within your reach uses a manipulate or move action, makes a ranged attack, or leaves a square during a move action it's using, you can attempt a melee Strike against it.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    trigger:
      "A creature within your reach uses a manipulate action, a move action, makes a ranged attack, or leaves a square during a move.",
    traits: { connect: [] },
  },
  {
    id: featIds.shieldBlock,
    name: "Shield Block",
    description:
      "You snap your shield in place to deflect a blow. Your shield prevents you from taking an amount of damage up to the shield's Hardness. You and the shield each take any remaining damage, potentially breaking or destroying the shield.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    trigger: "While you have your shield raised, you would take damage from a physical attack.",
    requirements: "You have your shield raised.",
    traits: { connect: [] },
  },
  {
    id: featIds.reactiveShield,
    name: "Reactive Shield",
    description:
      "You can snap your shield into place just as you need it. Raise your Shield as a reaction triggered by an attack.",
    featType: FeatType.Bonus,
    level: 2,
    actionCost: ActionCost.Reaction,
    rarity: Rarity.Common,
    trigger: "An enemy hits you with a melee Strike.",
    requirements: "You are wielding a shield.",
    traits: { connect: [] },
  },
  {
    id: featIds.quickShieldBlock,
    name: "Quick Shield Block",
    description:
      "You are able to block multiple attacks in rapid succession. You gain an additional reaction that can be used only for a Shield Block.",
    featType: FeatType.Bonus,
    level: 6,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    prerequisites: "Shield Block",
    traits: { connect: [] },
  },
  {
    id: featIds.battleMedicine,
    name: "Battle Medicine",
    description:
      "You can patch up wounds, even in the heat of battle. Attempt a Medicine check to Treat Wounds on a willing adjacent creature. This doesn't require healer's tools, and the target is temporarily immune for 1 day.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    prerequisites: "Trained in Medicine",
    traits: { connect: [] },
  },
  {
    id: featIds.breathControl,
    name: "Breath Control",
    description:
      "You have incredible control over your breathing. You can hold your breath for 25 times as long as usual before suffocating. You gain a +1 circumstance bonus to saving throws against inhaled threats.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.courtlyGraces,
    name: "Courtly Graces",
    description:
      "You were raised among the nobility. You can use Society to Make an Impression on a noble or to Impersonate a noble, even without a disguise.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    prerequisites: "Trained in Society",
    traits: { connect: [] },
  },
  {
    id: featIds.quickDraw,
    name: "Quick Draw",
    description:
      "You draw your weapon and attack in one swift motion. Draw a weapon, then make a Strike with it. If you have the Quick Draw ranger feat, you can also Interact to draw a shield.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.One,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.riskySurgery,
    name: "Risky Surgery",
    description:
      "Your surgery can risk your patient's life to heal them more. When you Treat Wounds, you can deal 1d8 slashing damage to the patient to gain a +2 circumstance bonus to your Medicine check.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    prerequisites: "Trained in Medicine",
    traits: { connect: [] },
  },
  {
    id: featIds.terrifyingResistance,
    name: "Terrifying Resistance",
    description:
      "Your mental fortitude makes you harder to frighten. You gain a +1 circumstance bonus to saving throws against fear effects and to your Will DC against Demoralize.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.naturalSkill,
    name: "Natural Skill",
    description:
      "Your ingenuity allows you to pick up new skills with ease. Gain training in two skills of your choice.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
  {
    id: featIds.sureFooting,
    name: "Sure Footing",
    description:
      "You rarely lose your footing even on unstable ground. When you roll a critical failure on an Acrobatics check to Balance, you get a failure instead, and you don't fall prone.",
    featType: FeatType.Bonus,
    level: 1,
    actionCost: ActionCost.None,
    rarity: Rarity.Common,
    traits: { connect: [] },
  },
];

export const seedLocalFeats = async (): Promise<{
  feats: Prisma.FeatUncheckedCreateInput[];
}> => {
  const feats = buildLocalFeats();
  await prisma.$transaction(
    feats.map((feat) => prisma.feat.create({ data: feat }))
  );
  return { feats };
};
